PROTOCOL_VERSION = 1
MAX_JSON_BYTES = 4096
SAFE_BLE_CHUNK_BYTES = 20

ACTION_SYSTEM_HELLO = "system.hello"
ACTION_SYSTEM_TIME_READ = "system.time.read"
ACTION_CODEX_USAGE_READ = "codex.usage.read"

RESULT_CODES = frozenset(
    {"OK", "NOT_LOGGED_IN", "BUSY", "CODEX_UNAVAILABLE", "TIMEOUT", "INVALID_RESPONSE", "ERROR"}
)

GATT_SERVICE_UUID = "5fd5b6a4-60a1-48e1-a4f3-69c9cab741d2"
GATT_ADV_TO_PC_NOTIFY_UUID = "a6c791a8-824d-4f3c-8708-0a05c8287ba3"
GATT_PC_TO_ADV_WRITE_UUID = "7d913c17-e2dd-4c15-b9c2-d1ba4e372ef3"

ACTION_ACTIONS_LIST = "actions.list"
ACTION_SCRIPTS_EXECUTE = "scripts.execute"
ACTION_SHORTCUT_EXECUTE = "actions.shortcut.execute"
SCRIPT_PAGE_SIZE = 8
